# Set update schedule for GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    target-branch: "dev"
  - package-ecosystem: "pip"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    target-branch: "dev"

  - package-ecosystem: pip
    directory: /.github/workflows
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /doc
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /test
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /test/standalone
    schedule:
      interval: daily
