language: python
python:
- 2.7
- 3.5
sudo: false
os:
- linux
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
      - python-dev
install:
- wget -O aerospike-server.tgz http://aerospike.com/download/server/latest/artifact/tgz
- tar xvzf aerospike-server.tgz
- cp -f .travis/aerospike.conf ./aerospike-server/share/etc
- cd aerospike-server
- sed -i -e 's/\${me}/"root"/' share/libexec/aerospike-start
- sed -i -e 's/set_shmall$/#set_shmall/' share/libexec/aerospike-start
- sed -i -e 's/set_shmmax$/#set_shmmax/' share/libexec/aerospike-start
- mkdir instance1
- mkdir instance2
- ./bin/aerospike init --home instance1 --instance 1 --service-port 3000
- ./bin/aerospike init --home instance2 --instance 2 --service-port 3010
- cd instance1
- ./bin/aerospike start
- ../../scripts/wait-for-node.sh var/log/aerospike.log
- cd ..
- cd instance2
- ./bin/aerospike start
- ../../scripts/wait-for-node.sh var/log/aerospike.log
- cd ../..
script:
- python setup.py install --lua-system-path=./
- cd test
- ./run -v
notifications:
  slack:
    secure: QaCE4lTfpv57X921q5oCrHrB1qqkLsnGM2+L/zCTEQKc20tNnfNjrDsFJGrLibZbEvZCcVOfr1xH0WhaPurngG6uTRLUqWBf3evwnMgTWDxFU0wcZlKR/Vww3zNXBuD4tDafC1bEa/fm+9xDDmtlV8AaySpiwQazLtwqOatoTD8=
  hipchat:
    rooms:
      secure: LmFIM1e/9Vr4Fx7abosnnc5gsgnSTCiOBSJlA62CeHa7xnOcz7k6LCw7VVtwZIaxnszDxMRx5Jn0d8P7JhX6XRu1BveWB9Ybpuan9i3+F+lHBusKMw5vFShquran//K1O3Or81rBxXc27Rd9K05rnH0747mlr2fNSfDJv2wygdI=
  email:
  - qe-notices@aerospike.com
  - qe-notices-clients@aerospike.com
