on:
  pull_request:
    paths:
    - aerospike-client-c
    - src/**
  workflow_dispatch:

jobs:
  build-c-client-submodule:
    uses: ./.github/workflows/build-c-client.yml

  build-python-client:
    needs: build-c-client-submodule
    uses: ./.github/workflows/build-python-client.yml
