on:
  workflow_call:

jobs:
  build-python-client:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        py-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - run: echo C_CLIENT_REVISION=$(git submodule status | awk '{print $1}') >> $GITHUB_ENV

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-version }}
        architecture: 'x64'
        allow-prereleases: true

    - run: sudo apt update
    - name: Install build dependencies (apt packages)
      run: sudo apt install python3-dev libssl-dev -y
    - name: Install build dependencies (pip packages)
      run: python3 -m pip install -r requirements.txt

    - uses: actions/cache/restore@v5
      id: download-c-client
      with:
        key: c-client-${{ env.C_CLIENT_REVISION }}
        path: libaerospike.a

    - name: Build client
      run: python3 -m build
      env:
        CFLAGS: '-Werror'
        C_CLIENT_SHARED_PATH: ./libaerospike.a

    - run: echo WHEEL_GH_ARTIFACT_NAME=wheel-${{ matrix.py-version }} >> $GITHUB_ENV

    - name: Send wheel to test jobs
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.WHEEL_GH_ARTIFACT_NAME }}
        path: ./dist/*.whl
