name: Documentation tests
permissions:
  contents: read

on:
  pull_request:
    paths:
      # doc8.ini not committed because it will cause pre-commit hooks to fail,
      # which will lead to changes to the below files anyways
    - '.github/workflows/doc-tests.yml'
    - 'doc/**/*'
    - 'aerospike_helpers/**/*'
  push:
    # To any central branch
    branches:
      - "dev*"
      - "stage*"
      - "master*"
      - "v*-backport*"
  # For debugging this workflow
  workflow_dispatch:

jobs:
  sphinx:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        builder-command:
        - 'spelling . spelling -W --keep-going'
        # -vv is too verbose and makes it hard to read logs
        - 'linkcheck -v . links'
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
      with:
        egress-policy: audit

    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        submodules: recursive
    - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: 3.11
        architecture: 'x64'
    - name: Install dependencies
      # TODO: find way to split up dependencies
      run: python -m pip install -r doc/requirements.txt
    - name: Run builder
      run: sphinx-build -b ${{ matrix.builder-command }}
      working-directory: doc
