# As of this writing, there are no Github Actions in the marketplace
# that allow fast forwarding using a personal access token
# So we need to use this for now
name: 'Fast forward merge'
on:
  workflow_dispatch:
    inputs:
      ref_to_merge:
        type: string
        required: true
      base_branch:
        type: string
        required: true
  workflow_call:
    inputs:
      # If another branch, it must be origin/<branch>
      ref_to_merge:
        type: string
        required: true
      base_branch:
        type: string
        required: true
    secrets:
      CLIENT_BOT_PAT:
        required: true

jobs:
  merge:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # Fetch the whole history to prevent unrelated history errors
          fetch-depth: '0'
          ref: ${{ inputs.base_branch }}
          token: ${{ secrets.CLIENT_BOT_PAT }}

      - name: Fast forward
        run: git merge --ff-only ${{ inputs.ref_to_merge }}

      - name: Upload changes to remote head branch
        run: git push
